%% graph LR;
%%     A-->N-->|YES|B;
%%     A-->C;
%%     B-->D;
%%     C-->B;

graph LR;
    American[American];
    English[English];
    French[French];
    German[German];
    Canadian[Canadian];

    Polite[Is polite]-->English;
    Polite-->G([And]);
    Stylish[Stylish clothes]-->G-->Elegant[Elegant]-->OR_2([OR]);
    Museums[Visits museums]-->K([And]);
    Traditional[Visits traditional foods restaurants]-->K;
    Authentic[Looks for authentic experiences]-->K;
    K-->History[Interested in history and culture]-->OR_2-->Intelectual[Intelectual]-->French;
    Accent[Has weird accent]-->English

    Pubs[Visits local pubs]-->Q([And]);
    Loud[Is loud]-->Q-->Drinks[Drinks a lot]-->English

    Time[Is always on time]-->U([And]);
    Curse[Doesn't curse?]-->U-->Rules[Respects rules];

    God[Says `God save the king` a lot]-->OR([OR]);
    Y[Has a flag on T-Shirt]-->OR-->Patriotic[Is patriotic]-->English
    Patriotic-->American

    Scarf[Wears a scarf]-->French;
