graph LR;
    American[American];
    English[British];
    French[French];
    German[German];
    Canadian[Canadian];
    Loonie[Loonie];

    Sorry[Apologizes a lot]-->OR_5;
    Friendly[Is friendly]-->OR_5([OR]);
    Sorry-->Canadian
    
    Polite[Is polite]-->English;
    OR_5-->Polite;
    Blue[Has blonde hair and blue eyes]-->German;
    Museums[Visits museums]-->Or([OR]);
    Traditional[Visits traditional restaurants]-->Or;
    Or-->Culture[Interested in culture]-->AND_4-->Intelectual[Intelectual]-->French;
    Accent[Has weird accent]-->English

    Pubs[Visits local pubs]-->OR_6([OR]);

    Time[Is always on time]-->German;
    Polite-->AND_6([And]);
    Curse[Doesn't curse]-->AND_6-->Rules[Respects rules]-->German;

    God[Says `God save the king` a lot]-->OR([OR]);
    Flag[Has a flag on T-Shirt]-->OR-->Patriotic[Is patriotic]-->English
    Loud[Is loud]-->OR_6-->Drinks[Drinks a lot]-->English
    Stylish[Is stylish]-->AND_4([And]);
    Patriotic-->American
    LocalLanguage[Speaks local language]-->Loonie;
    FastFood[Visits fast food places]-->American;
    Smiles[Smiles a lot]-->American;

    Scarf[Wears a scarf]-->French;
    Drinks-->German;

    Beard[Has a long beard]-->OR_4;

    Clothes[Weirs a red plaid shirt]-->Canadian;

    Culture-->Loonie;
    Hair[Has messy hair]-->OR_4([OR])-->Style[Doesn't care about style]-->Canadian;